/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WeeklyRouteImport } from './routes/weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/planner': typeof PlannerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/planner': typeof PlannerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/monthly': typeof MonthlyRoute
  '/planner': typeof PlannerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/goals'
    | '/home'
    | '/insights'
    | '/monthly'
    | '/planner'
    | '/reset-password'
    | '/review'
    | '/routines'
    | '/settings'
    | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/goals'
    | '/home'
    | '/insights'
    | '/monthly'
    | '/planner'
    | '/reset-password'
    | '/review'
    | '/routines'
    | '/settings'
    | '/weekly'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/daily'
    | '/goals'
    | '/home'
    | '/insights'
    | '/monthly'
    | '/planner'
    | '/reset-password'
    | '/review'
    | '/routines'
    | '/settings'
    | '/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DailyRoute: typeof DailyRoute
  GoalsRoute: typeof GoalsRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  MonthlyRoute: typeof MonthlyRoute
  PlannerRoute: typeof PlannerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  WeeklyRoute: typeof WeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DailyRoute: DailyRoute,
  GoalsRoute: GoalsRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  MonthlyRoute: MonthlyRoute,
  PlannerRoute: PlannerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  WeeklyRoute: WeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
